sample_size: 32
flip_sin_to_cos: False
dual_fno: True
freq_shift: 1
in_channels: 3
out_channels: 3
layers_per_block: 2
block_out_channels: [128, 256, 256, 256]
block_samples: [32, 16, 8, 4]
down_block_types: [
    "FNODownBlock2D",
    "FNODownBlock2D",
    "AttnDownBlock2D",
    "DownBlock2D",
]
up_block_types: [
    "UpBlock2D",
    "AttnUpBlock2D",
    "FNOUpBlock2D",
    "FNOUpBlock2D",
]