sample_size: 32
flip_sin_to_cos: False
freq_shift: 1
in_channels: 3
out_channels: 3
layers_per_block: 2
block_out_channels: [128, 256, 256, 256]
down_block_types: [
    "DownBlock2D",
    "DownBlock2D",
    "AttnDownBlock2D",
    "DownBlock2D",
]
up_block_types: [
    "UpBlock2D",
    "AttnUpBlock2D",
    "UpBlock2D",
    "UpBlock2D",
]