sample_size: 64
in_channels: 3
out_channels: 3
layers_per_block: 2
block_out_channels: [128, 256, 256,]
block_samples: [64, 32, 16]
down_block_types: [
    "FNODownBlock2D",
    "AttnDownBlock2D",
    "FNODownBlock2D",
]
up_block_types: [
    "FNOUpBlock2D",
    "AttnUpBlock2D",
    "FNOUpBlock2D",
]
verbose: False