sample_size: 256
flip_sin_to_cos: False
freq_shift: 1
in_channels: 3
out_channels: 3
layers_per_block: 2
block_out_channels: [128, 128, 256, 256, 512, 512]
block_samples: [32, 16, -1, -1, -1, -1]
down_block_types: [
    "FNODownBlock2D",
    "FNODownBlock2D",
    "DownBlock2D",
    "DownBlock2D",
    "AttnDownBlock2D",
    "DownBlock2D",
]
up_block_types: [
    "UpBlock2D",
    "AttnUpBlock2D",
    "UpBlock2D",
    "UpBlock2D",
    "FNOUpBlock2D",
    "FNOUpBlock2D",
]
verbose: False